[package]
name = "msquic"
version = "1.5.0"
edition = "2018"
authors = ["Microsoft"]
description = "Microsoft implementation of the IETF QUIC protocol"
readme = "README.md"
repository = "https://github.com/microsoft/msquic/"
license = "MIT"
categories = ["network-programming", "asynchronous"]
keywords = ["quic", "network", "secure"]
build = "src/build.rs"
include = [
    "/*.md",
    "/*.toml",
    "/LICENSE",
    "/submodules/openssl",
    "/src/*.rs",
    "/src/bin",
    "/src/core",
    "/src/inc",
    "/src/manifest",
    "/src/platform",
    "/THIRD-PARTY-NOTICES",
]

[dependencies]
libc = "0.2.0"
