# This template contains steps to use Cargo to build MsQuic Rust library.

parameters:
  image: ''
  platform: ''

jobs:
- job: cargo_${{ parameters.platform }}
  displayName: Cargo ${{ parameters.image }}
  pool:
    vmImage: ${{ parameters.image }}
  steps:
  - checkout: self
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: cargo build --all
    displayName: Cargo build
  - script: cargo test --all
    displayName: Cargo test
